export let datae = [
  { id: 1, lastName: "Smith", firstName: "John", age: 30 },
  { id: 2, lastName: "Johnson", firstName: "Alice", age: 25 },
  { id: 3, lastName: "Williams", firstName: "Bob", age: 40 },
  { id: 4, lastName: "Jones", firstName: "Emma", age: 28 },
  { id: 5, lastName: "Davis", firstName: "Michael", age: 50 },
  { id: 6, lastName: "Miller", firstName: "Olivia", age: 22 },
  { id: 7, lastName: "Wilson", firstName: "Christopher", age: 35 },
  { id: 8, lastName: "Moore", firstName: "Sophia", age: 32 },
  { id: 9, lastName: "Taylor", firstName: "David", age: 45 },
  { id: 10, lastName: "Brown", firstName: "Mia", age: 27 },
  { id: 11, lastName: "Anderson", firstName: "Daniel", age: 38 },
  { id: 12, lastName: "Jackson", firstName: "Ava", age: 33 },
  { id: 13, lastName: "White", firstName: "Liam", age: 29 },
  { id: 14, lastName: "Harris", firstName: "Sophie", age: 31 },
  { id: 15, lastName: "Martin", firstName: "Matthew", age: 48 },
  { id: 16, lastName: "Thompson", firstName: "Chloe", age: 26 },
  { id: 17, lastName: "Robinson", firstName: "Ethan", age: 37 },
  { id: 18, lastName: "Clark", firstName: "Emily", age: 23 },
  { id: 19, lastName: "Lewis", firstName: "Jackson", age: 42 },
  { id: 20, lastName: "Hall", firstName: "Avery", age: 24 },
  { id: 21, lastName: "Walker", firstName: "Scarlett", age: 34 },
  { id: 22, lastName: "Young", firstName: "Noah", age: 39 },
  { id: 23, lastName: "Hill", firstName: "Grace", age: 36 },
  { id: 24, lastName: "Turner", firstName: "Logan", age: 41 },
  { id: 25, lastName: "Cooper", firstName: "Lily", age: 21 },
  { id: 26, lastName: "Ward", firstName: "Samuel", age: 44 },
  { id: 27, lastName: "Morgan", firstName: "Hannah", age: 28 },
  { id: 28, lastName: "Reed", firstName: "Owen", age: 37 },
  { id: 29, lastName: "Carter", firstName: "Ella", age: 32 },
  { id: 30, lastName: "Fisher", firstName: "William", age: 46 },
  { id: 31, lastName: "Bennett", firstName: "Aria", age: 25 },
  { id: 32, lastName: "Lane", firstName: "Isaac", age: 30 },
  { id: 33, lastName: "Graham", firstName: "Ava", age: 33 },
  { id: 34, lastName: "Kelly", firstName: "Daniel", age: 39 },
  { id: 35, lastName: "Burke", firstName: "Zoe", age: 27 },
  { id: 36, lastName: "Wells", firstName: "Landon", age: 42 },
  { id: 37, lastName: "Bryant", firstName: "Eva", age: 31 },
  { id: 38, lastName: "Cole", firstName: "Nathan", age: 38 },
  { id: 39, lastName: "Gomez", firstName: "Mila", age: 29 },
  { id: 40, lastName: "Lloyd", firstName: "Caleb", age: 34 },
  { id: 41, lastName: "Hansen", firstName: "Avery", age: 26 },
  { id: 42, lastName: "Hudson", firstName: "Madison", age: 22 },
  { id: 43, lastName: "Fleming", firstName: "Elijah", age: 35 },
  { id: 44, lastName: "Reyes", firstName: "Aria", age: 30 },
  { id: 45, lastName: "Nelson", firstName: "Evan", age: 28 },
  { id: 46, lastName: "Thornton", firstName: "Piper", age: 23 },
  { id: 47, lastName: "Gordon", firstName: "Carter", age: 41 },
  { id: 48, lastName: "Moss", firstName: "Hailey", age: 24 },
  { id: 49, lastName: "Bates", firstName: "Mason", age: 37 },
  { id: 50, lastName: "Hampton", firstName: "Luna", age: 33 },
  { id: 51, lastName: "Johnson", firstName: "Michael", age: 28 },
  { id: 52, lastName: "Smith", firstName: "Emily", age: 35 },
  { id: 53, lastName: "Williams", firstName: "Daniel", age: 42 },
  { id: 54, lastName: "Jones", firstName: "Olivia", age: 24 },
  { id: 55, lastName: "Davis", firstName: "Christopher", age: 30 },
  { id: 56, lastName: "Miller", firstName: "Sophia", age: 22 },
  { id: 57, lastName: "Wilson", firstName: "Ethan", age: 38 },
  { id: 58, lastName: "Moore", firstName: "Ava", age: 31 },
  { id: 59, lastName: "Taylor", firstName: "William", age: 45 },
  { id: 60, lastName: "Brown", firstName: "Emma", age: 29 },
  { id: 61, lastName: "Anderson", firstName: "Liam", age: 27 },
  { id: 62, lastName: "Thomas", firstName: "Isabella", age: 33 },
  { id: 63, lastName: "Jackson", firstName: "Mia", age: 26 },
  { id: 64, lastName: "White", firstName: "James", age: 40 },
  { id: 65, lastName: "Harris", firstName: "Sophie", age: 36 },
  { id: 66, lastName: "Martin", firstName: "Alexander", age: 34 },
  { id: 67, lastName: "Thompson", firstName: "Grace", age: 23 },
  { id: 68, lastName: "Garcia", firstName: "Logan", age: 32 },
  { id: 69, lastName: "Martinez", firstName: "Ella", age: 41 },
  { id: 70, lastName: "Robinson", firstName: "Andrew", age: 39 },
  { id: 71, lastName: "Clark", firstName: "Avery", age: 25 },
  { id: 72, lastName: "Lee", firstName: "Harper", age: 20 },
  { id: 73, lastName: "Walker", firstName: "Benjamin", age: 37 },
  { id: 74, lastName: "Hall", firstName: "Natalie", age: 29 },
  { id: 75, lastName: "Young", firstName: "Jackson", age: 43 },
  { id: 76, lastName: "Hill", firstName: "Chloe", age: 21 },
  { id: 77, lastName: "Adams", firstName: "Lucas", age: 44 },
  { id: 78, lastName: "Ward", firstName: "Lily", age: 19 },
  { id: 79, lastName: "Cook", firstName: "Nicholas", age: 46 },
  { id: 80, lastName: "Cooper", firstName: "Madison", age: 22 },
  { id: 81, lastName: "Ross", firstName: "Gabriel", age: 38 },
  { id: 82, lastName: "Morgan", firstName: "Hannah", age: 33 },
  { id: 83, lastName: "Baker", firstName: "Matthew", age: 30 },
  { id: 84, lastName: "Diaz", firstName: "Aria", age: 23 },
  { id: 85, lastName: "Hayes", firstName: "Caleb", age: 36 },
  { id: 86, lastName: "Wells", firstName: "Victoria", age: 27 },
  { id: 87, lastName: "Barnes", firstName: "Elijah", age: 31 },
  { id: 88, lastName: "Fisher", firstName: "Alyssa", age: 25 },
  { id: 89, lastName: "Harrison", firstName: "Dylan", age: 29 },
  { id: 90, lastName: "Woods", firstName: "Zoe", age: 26 },
  { id: 91, lastName: "Sanders", firstName: "Joseph", age: 34 },
  { id: 92, lastName: "Reed", firstName: "Mila", age: 28 },
  { id: 93, lastName: "Ramirez", firstName: "Jayden", age: 32 },
  { id: 94, lastName: "Evans", firstName: "Ava", age: 39 },
  { id: 95, lastName: "Fletcher", firstName: "Evan", age: 35 },
  { id: 96, lastName: "Simmons", firstName: "Addison", age: 24 },
  { id: 97, lastName: "Perez", firstName: "Connor", age: 37 },
  { id: 98, lastName: "Brooks", firstName: "Scarlett", age: 21 },
  { id: 99, lastName: "Gomez", firstName: "Cameron", age: 40 },
  { id: 100, lastName: "Bryant", firstName: "Layla", age: 26 },
];
export const data = [
  { name: 'John', age: 25, city: 'New York' },
  { name: 'Alice', age: 30, city: 'San Francisco' },
  { name: 'Michael', age: 22, city: 'Los Angeles' },
  { name: 'Emily', age: 28, city: 'Chicago' },
  { name: 'Daniel', age: 35, city: 'Houston' },
  { name: 'Sophia', age: 27, city: 'Miami' },
  { name: 'Matthew', age: 32, city: 'Seattle' },
  { name: 'Olivia', age: 26, city: 'Denver' },
  { name: 'David', age: 40, city: 'Boston' },
  { name: 'Emma', age: 31, city: 'Atlanta' },
  { name: 'Ethan', age: 29, city: 'Philadelphia' },
  { name: 'Ava', age: 33, city: 'Phoenix' },
  { name: 'Ryan', age: 24, city: 'Dallas' },
  { name: 'Mia', age: 36, city: 'Detroit' },
  { name: 'Christopher', age: 23, city: 'Minneapolis' },
  { name: 'Sophie', age: 34, city: 'Portland' },
  { name: 'Nathan', age: 37, city: 'Charlotte' },
  { name: 'Lily', age: 28, city: 'San Diego' },
  { name: 'Benjamin', age: 26, city: 'Austin' },
  { name: 'Hannah', age: 31, city: 'Nashville' },
  { name: 'James', age: 29, city: 'Raleigh' },
  { name: 'Aiden', age: 38, city: 'Indianapolis' },
  { name: 'Avery', age: 27, city: 'Columbus' },
  { name: 'Jackson', age: 25, city: 'Las Vegas' },
  { name: 'Madison', age: 32, city: 'Kansas City' },
  { name: 'Lucas', age: 30, city: 'San Antonio' },
  { name: 'Chloe', age: 24, city: 'Memphis' },
  { name: 'Caleb', age: 33, city: 'Tampa' },
  { name: 'Grace', age: 35, city: 'St. Louis' },
  { name: 'Liam', age: 26, city: 'Salt Lake City' },
  { name: 'Zoe', age: 29, city: 'Pittsburgh' },
  { name: 'Elijah', age: 31, city: 'Orlando' },
  { name: 'Natalie', age: 28, city: 'Baltimore' },
  { name: 'Logan', age: 27, city: 'Milwaukee' },
  { name: 'Aria', age: 34, city: 'Albuquerque' },
  { name: 'Evan', age: 36, city: 'Hartford' },
  { name: 'Aubrey', age: 23, city: 'Louisville' },
  { name: 'Wyatt', age: 30, city: 'Oklahoma City' },
  { name: 'Hailey', age: 25, city: 'Buffalo' },
  { name: 'Mason', age: 32, city: 'Richmond' },
  { name: 'Isabella', age: 29, city: 'El Paso' },
  { name: 'Luke', age: 28, city: 'Birmingham' },
  { name: 'Scarlett', age: 31, city: 'Tucson' },
  { name: 'Owen', age: 26, city: 'Fresno' },
  { name: 'Layla', age: 33, city: 'Sacramento' },
  { name: 'Hunter', age: 27, city: 'Honolulu' },
  { name: 'Penelope', age: 30, city: 'Boise' },
  { name: 'Gabriel', age: 29, city: 'Des Moines' }
]
export const columns = [
  { id: 'name', label: 'Name', minWidth: 100 },
  { id: 'age', label: 'Age', minWidth: 50 },
  { id: 'city', label: 'City', minWidth: 100 },
  // Add more columns as needed
];